In [38]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
np.arange(100).reshape(10,10)

array([ 45., 145., 245., 345., 445., 545., 645., 745., 845., 945.])

## det 计算对角线和
## trace 计算对角线元素的和
## eig 计算方阵的本征值
## inv 计算方阵的逆

## 随机漫步
## 什么时候距离初逝点为10步

In [51]:
np.full(10,100)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

# 随机漫步代码

In [62]:
position = 0
walk = [position]
steps = 1000  # 累积走的位置数量
expr = 10 # 要求的到达距离
for i in range(steps):
    step = 1 if np.random.randint(0,2) else -1 # 随机前进或者后退一步 1，-1
    position += step # 累积步长
    walk.append(position) 
plt.figure(figsize=(16,9))
plt.plot(walk)
plt.plot(np.full(steps,10))
(np.abs(walk)>expr).argmax()

19

# 有几次到达了指定位置

In [67]:
(np.array(walk)==expr).sum()

5

# 到达指定位置的步数分别是

In [68]:
np.argwhere(np.array(walk)==expr)

array([[384],
       [386],
       [388],
       [390],
       [392]])