In [82]:
import torch as t
import numpy as np

In [83]:
a = [['2','1','0','1','0','2','0','2','1','1'],[1,2,3,1,"a"]]

In [84]:
b = ['2','1','0','1','0','2']

In [85]:
def dim_reduce(lists):
    return [j for i in lists for j in i]
a = dim_reduce(a)
a

['2', '1', '0', '1', '0', '2', '0', '2', '1', '1', 1, 2, 3, 1, 'a']

In [86]:
unique = np.unique(a)
index_src = np.array([np.argwhere(unique==element)[0][0] for element in b])
index_src

array([2, 1, 0, 1, 0, 2])

In [88]:
out = torch.zeros(index_src.size,unique.size)
out

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [89]:
index = torch.LongTensor(index_src).view(-1,1)
index

tensor([[2],
        [1],
        [0],
        [1],
        [0],
        [2]])

In [93]:
out.scatter_(dim=1,index=index,value=1)

tensor([[0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

# 计数

In [94]:
from sklearn.feature_extraction.text import CountVectorizer
import jieba

data = jieba.cut("网易是中国领先的互联网技术公司，为用户提供免费邮箱、游戏、搜索引擎服务，开设新闻、娱乐、体育等30多个内容频道，及博客、视频、论坛等互动交流，网聚人的力量, 网易评论不错哦")
# for temp in data:
#     print(temp)
data = ' '.join(data)
print(data)
vector = CountVectorizer()
res = vector.fit_transform([data])
print(vector.get_feature_names())
print(res.toarray())

Building prefix dict from /usr/local/lib/python3.7/site-packages/jieba/dict.txt ...
Loading model from cache /var/folders/sl/q8x6_03132dfk7rktf00yh880000gn/T/jieba.cache
Loading model cost 0.9591760635375977 seconds.
Prefix dict has been built succesfully.
网易 是 中国 领先 的 互联网 技术 公司 ， 为 用户 提供 免费邮箱 、 游戏 、 搜索引擎 服务 ， 开设 新闻 、 娱乐 、 体育 等 30 多个 内容 频道 ， 及 博客 、 视频 、 论坛 等 互动 交流 ， 网聚 人 的 力量 ,   网易 评论 不错 哦
['30', '不错', '中国', '互动', '互联网', '交流', '体育', '免费邮箱', '公司', '内容', '力量', '博客', '多个', '娱乐', '开设', '技术', '提供', '搜索引擎', '新闻', '服务', '游戏', '用户', '网易', '网聚', '视频', '论坛', '评论', '领先', '频道']
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1]]


# one hot 编码

In [98]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
# 说所有的样本加起来必须保证所有列的特征值都要遍历到
enc.fit([['男', '中国', '足球'],
         ['女', '美国', '篮球'],
         ['男', '日本', '羽毛球'],
         ['女', '中国', '乒乓球']])  # 这里一共有4个数据，3种特征
array = enc.transform([['男', '美国', '乒乓球']]).toarray()  # 这里使用一个新的数据来测试
print(array)  # [[ 1  0  0  1  0  0  0  0  1]

[[0. 1. 0. 0. 1. 1. 0. 0. 0.]]


# one hot 解码

In [96]:
enc.inverse_transform(array)

array([['男', '美国', '乒乓球']], dtype=object)